package com.example.apitest.dataModel


import androidx.annotation.Keep
import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

@Keep
@JsonClass(generateAdapter = true)
data class UserDetails(
    @Json(name = "automatic_printing_bill")
    var automatic_printing_bill: Int? = null,
    @Json(name = "pos_product_double_line")
    var pos_product_double_line: Int? = null,
    @Json(name = "expense_status")
    var expense_status: Int? = null,
    @Json(name = "qr_scanner_status")
    var qr_scanner_status: Int? = null,
    @Json(name = "employee_based_report_status")
    var employee_based_report_status: Int? = null,
    @Json(name = "owner_status")
    var owner_status: Int? = null,
    @Json(name = "cart_mobile_number_search_status")
    var cart_mobile_number_search_status: String? = null,
    @Json(name = "order_available_status")
    var order_available_status: String? = null,
    @Json(name = "product_available_status")
    var product_available_status: String? = null,
    @Json(name = "reseller_code")
    var reseller_code: String? = null,
    @Json(name = "unit_status")
    var unit_status: String? = null,
    @Json(name = "quantity_status")
    var quantity_status: String? = null,
    @Json(name = "mobile_no_search_status")
    var mobile_no_search_status: String? = null,
    @Json(name = "address")
    var address: String? = null,
    @Json(name = "usage_limit_message")
    var usage_limit_message: String? = null,
    @Json(name = "shop_image")
    var shop_image: String? = null,
    @Json(name = "name")
    var name: String? = null,
    @Json(name = "password")
    var password: String? = null,
    @Json(name = "report_password")
    var report_password: String? = null,
    @Json(name = "incharge_name")
    var inchargeName: String? = null,
    @Json(name = "user_email")
    var userEmail: String? = null,
    @Json(name = "gst_num")
    var gst_num: String? = null,
    @Json(name = "user_id")
    var userId: Int? = null,
    @Json(name = "shop_tax")
    var shop_tax: Int? = null,
    @Json(name = "ac_status")
    var ac_status: String? = null,
    @Json(name = "stock_status")
    var stock_status: String? = null,
    @Json(name = "tax_status")
    var tax_status: String? = null,
    @Json(name = "user_image")
    var userImage: String? = null,
    @Json(name = "user_name")
    var userName: String? = null,
    @Json(name = "user_phone_number")
    var userPhoneNumber: String? = null,
    @Json(name = "whatapp_number")
    var whatapp_number: String? = null,
    @Json(name = "web_link")
    var web_link: String? = null,
    @Json(name = "customer_care_mobile")
    var customer_care_mobile: String? = null,
    @Json(name = "customer_care_mail")
    var customer_care_mail: String? = null,
    @Json(name = "city_id")
    var city_id: String? = null,
    @Json(name = "city_name")
    var city_name: String? = null,
    @Json(name = "printer_size")
    var printer_size: String? = null,
    @Json(name = "printer_size_id")
    var printer_size_id: String? = null,
    @Json(name = "printer_language_status")
    var printer_language_status: String? = null,
    @Json(name = "discount_type")
    var discount_type: String? = null,
    @Json(name = "shop_language")
    var shop_language: String? = null,
    @Json(name = "printer_connection")
    var printer_connection: String? = null,
    @Json(name = "gpay_number")
    var gpay_number: String? = null,
    @Json(name = "double_print_status")
    var double_print_status: String? = null,
    @Json(name = "footer_text1")
    var footer_text1: String? = null,
    @Json(name = "footer_text2")
    var footer_text2: String? = null,
    @Json(name = "estimation_bill_status")
    var estimation_bill_status: String? = null,
    @Json(name = "advance_payment_status")
    var advance_payment_status: String? = null,
    @Json(name = "invoice_share_status")
    var invoice_share_status: String? = null,
    @Json(name = "settings_status")
    var settings_status: Int? = null,
    @Json(name = "report_status")
    var report_status: Int? = null,
    @Json(name = "inventory_status")
    var inventory_status: Int? = null,
    @Json(name = "employee_stock_status")
    var employee_stock_status: Int? = null,
    @Json(name = "emp_name")
    var emp_name: String? = null,
    @Json(name = "employee_phone_number")
    var employee_phone_number: String? = null,
    @Json(name = "bill_number_prefix")
    var bill_number_prefix: String? = null,
    @Json(name = "customized_bill_title")
    var customized_bill_title: String? = null,
    @Json(name = "custom_product_status")
    var custom_product_status: String? = null,
    @Json(name = "mrp_price_status")
    var mrp_price_status: String? = null,
    @Json(name = "whole_sale_price_status")
    var whole_sale_price_status: String? = null,
    @Json(name = "product_tax_status")
    var product_tax_status: String? = null,
)